---
title: "Final_Workspace"
format: html
editor: source
---


```{r}
#| include: false
library(sf)
library(leaflet)
library(htmltools)
library(glue)
library(tidyverse)
library(polite)
library(rvest)
```

```{r}
#| label: loading in datasets, making them match
#| include: false

# original parks list
final_parks <- read_csv("final_parks.csv") |>
  mutate(name = case_when(
    name == "Cascade River State Park Recreation Site" ~ "Cascade River State Park",
    name == "Killen Woods State Park" ~ "Kilen Woods State Park",
    name == "John Latsch State Park" ~ "John A Latsch State Park",
    name == "Nerstrand Woods State Park" ~ "Nerstrand Big Woods State Park",
    name == "Sakatah State Park" ~ "Sakatah Lake State Park",
    name == "O L Kipp State Park" ~ "Great River Bluffs State Park",
    name == "Saint Croix Wild River State Park" ~ "Wild River State Park",
    name == "Helmer Myre State Park" ~ "Myre-Big Island State Park",
    .default = name
    ))

# polygon data by park
park_polygons <- read_sf("Dnr_Stat_Plan_Areas_Prk.geojson") |>
  mutate(legislative_name = str_replace_all(legislative_name, "\\.", ""),
         legislative_name = ifelse(legislative_name == "St Croix State Park", "Saint Croix State Park", legislative_name))
```

```{r}
#| label: scraping missing park data
#| include: false

#list of names of parks with missing info
name <- c("Crow Wing", "Forestville Mystery Cave", "Franz Jevne", "Glendalough", "Grand Portage", "Lac qui Parle", "Lake Louise", "Lake Shetek", "Lake Vermilion-Soudan Underground Mine", "Monson Lake", "Moose Lake", "Rice Lake", "Savanna Portage", "Schoolcraft", "Cascade River", "Father Hennepin", "Myre-Big Island", "Great River Bluffs", "Wild River")

#unique id number in each park url
web_id <- c(139, 148, 157, 167, 173, 197, 214, 220, 285, 238, 239, 250, 259, 263, 133, 142, 175, 244, 254)

# checking scraping allowed
robotstxt::paths_allowed("https://www.dnr.state.mn.us/")

# checking conditions
session <- bow("https://www.dnr.state.mn.us/state_parks/list_alpha.html", force = TRUE)

# making list of urls
urls <- vector("character")
for (i in 1:length(web_id)) {
  url <- str_c("https://www.dnr.state.mn.us/state_parks/park.html?id=spk00", web_id[i], "#information")
  urls <- c(urls, url)
}

# scraping each page
scrape_park_info <- function(url) {
  Sys.sleep(5)
  session <- bow(url, force = TRUE)
  scrape(session) |>
    html_nodes("meta[name='dc.description']") |> # this scrapes the park description
    html_attr("content")
}

# building outside of the function
Sys.sleep(5)
  session <- bow(urls[1], force = TRUE)
  scrape(session) |>
    html_nodes("meta[name='dc.description']") |>
    html_attr("content")

# getting descriptions
description <- vector("character")
for (i in 1:length(urls)) {
  park_url <- urls[i]
  paragraph <- scrape_park_info(park_url)
  description <- c(description, paragraph) 
}

# puts all the scraped data in a table
missing <- tibble(name, description) |>
  mutate(name = str_c(name, " State Park"))

# makes a full dataset with original + missing data
new <- final_parks |>
  full_join(missing, by = "name") |> # this makes sure that rows that don't 
  # match are kept
  mutate(description = coalesce(description.x, description.y), # combines the
         # description rows from each dataset
         type = ifelse(is.na(type), "state park", type)) |>
  select(name, url, address, description, type)

#making a csv
write_csv(new, "parks_updated.csv")
```


```{r}
#| label: parks csv
#| include: false
parks <- read_csv("parks_updated.csv")
```





# added html labels, fixed for extra parks

```{r}
#| label: adding html labels
#| include: false
# joining polygons
parks_sf <- parks |>
  left_join(park_polygons, by = c("name" = "legislative_name"))

# adding html labels of name/description
parks_sf <- parks_sf |>
  mutate(labels = str_c("<p><strong>", name, "</strong></p>
<p><span style='font-weight: 400;'>", description, "</span></p>"))

# applying html
labels <- lapply(parks_sf$labels, HTML)

# making the dataframe sf
parks_sf <- st_as_sf(parks_sf)

# checking class
class(parks_sf)
```

```{r}
#| labels: making map
# making the map!
leaflet(parks_sf) |>
  setView(-93.8, 46.5, 6) |>
  addTiles() |>
  addPolygons(
    color = "darkred",
    fillColor = "darkred",
    fillOpacity = 1,
    weight = 2,
    opacity = 1,
    highlightOptions = highlightOptions(
      weight = 5,
      color = "red",
      bringToFront = TRUE),
    label = labels,
    labelOptions = popupOptions( 
      style = list("font-weight" = "normal", padding = "2px 5px", color = "black", "width" = "450px", "white-space" = "normal"),
      textsize = "15px",
      direction = "auto")
  )
```

# scraping wikipedia

```{r}
#| label: scraping wikipedia
#| include: false
session <- bow("https://en.wikipedia.org/wiki/List_of_Minnesota_state_parks", force = TRUE)

# scrapes the tables
result <- scrape(session) |>
  html_nodes(css = "table") |>
  html_table(header = TRUE, fill = TRUE)

# takes the table of interest about parks
try <- result[[1]]

# removes the extra row, removes HA space column, renames Acres column from Size[9]
try <- try[-1,] 
try <- try[,-4]
try <- try |> rename(Acres = `Size[9]`)

# removes . and / and renames parks to help with joining with the parks csv
wikipedia <- try |>
  mutate(`Park name` = str_replace_all(`Park name`, "[.]", "")) |>
  mutate(`Park name` = str_replace_all(`Park name`, "[/]", " ")) |>
  mutate(`Park name` = case_when(`Park name` == "Nerstrand-Big Woods State Park" ~ "Nerstrand Big Woods State Park",
         `Park name` == "St Croix State Park" ~ "Saint Croix State Park",
         `Park name` == "Lake Vermilion Soudan Underground Mine State Park" ~ "Lake Vermilion-Soudan Underground Mine State Park",
            .default = `Park name`),
         Coordinates = str_replace_all(Coordinates, "^.*nowrap\\}", "")) |>
  rename(name = `Park name`) |> #renames park name column to match final_parks
  mutate(Acres = parse_number(Acres)) |> #changes Acres from chr to num
  rename(Year = `Year Established[4]`) |> #renames column
  mutate(Year = str_sub(Year, 1, 4)) |> #removes extra brackets, leaves year
  mutate(Coordinates = str_replace_all(Coordinates, "^.*/ ", ""),
         Coordinates = str_replace_all(Coordinates, "\\(.*\\)", "")) |>
  separate_wider_delim(Coordinates, delim = ";", names = c("lat", "long")) |>
  mutate(long = str_trim(long), lat = str_trim(lat))

#left_joins the existing park data with the data from wikipedia
with_wiki <- wikipedia |>
  full_join(parks)

write_csv(with_wiki, "wiki_parks_data.csv")
```

```{r}
#| label: visit totals by season csv
#| include: false
#create csv with visit totals by park
visits <- read_csv("Seasonal_summary.csv")

by_season_visits <- 
  visits |>
  filter (`Unit type` == "State Park") |>
  mutate(visit_year = str_sub(Season, -4, -1)) |>
  mutate(Season = str_extract(Season, "[^-]+")) |>
  group_by(`Park name`, Season, visit_year) |>
  mutate(total = sum(`Vehicle visits`)) |>
  distinct(`Park name`, .keep_all = TRUE) |>
  select(`Park name`, `System`, `Implementing agency`, `Unit type`, `total`, visit_year, Season) |>
  rename(name = `Park name`) |>
  mutate(name = str_c(name, " State Park"))

write.csv(by_season_visits, "by_season_visits.csv")
```

```{r}
#| label: visit data and years
#| include: false
#joins visitation data with acres and year established data from wikipedia
numbers <- 
  with_wiki |>
  left_join(by_season_visits) |> 
  select(name, Season, total, Acres, `Year Established[4]`) |>
  rename(year = `Year Established[4]`) |>
  mutate(year = str_sub(year, 1, 4))

write.csv(numbers, "numbers.csv")
```


# second graph

```{r}
library(readr)

with_wiki <- read_csv("wiki_parks_data.csv")

numeric <- with_wiki |>
  mutate(long = str_replace_all(long, "^[^\\d]*", "-")) |>
  mutate(lat = as.numeric(lat), long = parse_number(long))
```

```{r}
county_parks <- numeric |>
  mutate(`County or Counties` = case_when(
    str_detect(`County or Counties`, "[a-z] and ") ~ str_replace_all(`County or Counties`, " and", ","),
    str_detect(`County or Counties`, "[a-z], and ") ~ str_replace_all(`County or Counties`, " and", ""),
    .default = `County or Counties`)) |>
  mutate(unpacked = str_split(`County or Counties`, ",")) |>
  filter(!is.na(unpacked)) |>
  unnest(cols = c(unpacked)) |>
  mutate(county = str_trim(unpacked)) |>
  #pivot_wider(names_from = county, values_from = n, values_fill = list(n = 0))
  group_by(county) |>
  mutate(num = n())
  
county_parks <- county_parks |>
  mutate(county = ifelse(county == "Murray County", "Murray", county))

```

# mapping
```{r}
county_polygons <- read_sf("Mn_County_Boundaries_Multipart.geojson")

county_maps <- county_parks |>
  right_join(county_polygons, by = c("county" = "countyname")) |>
  mutate(num = replace_na(num, 0))

pal <- colorFactor(c("white", "yellow2", "yellowgreen", "forestgreen", "cyan4", "blue4"), county_maps$num)

county_maps <- county_maps |>
  mutate(labels = str_c(county, " County: ", num, ifelse(num == 1, " state park", " state parks")),
         labels2 = name)

labels <- lapply(county_maps$labels, HTML)
labels2 <- lapply(county_maps$labels2, HTML)

county_maps <- st_as_sf(county_maps)
class(county_maps)

leaflet(county_maps) |>
  setView(-93.8, 46.5, 6) |>
  addTiles() |>
  addPolygons(
    fillColor = ~pal(num),
    weight = 2,
    opacity = 1,
    color = "white",
    dashArray = "3",
    fillOpacity = 0.7,
    ) |>
  addCircleMarkers(
    lng = ~long,
    lat = ~lat,
    radius = 2,
    color = "white",
    fillOpacity = 1,
    options = pathOptions(pane = "markerPane"),
    label = labels2,
    labelOptions = labelOptions(
      style = list("font-weight" = "normal", padding = "3px 8px", color = "black"),
      textsize = "15px",
      direction = "auto")
  ) |>
  addLegend(pal = pal, values = ~num, opacity = 0.7, title = NULL,
    position = "bottomright")
```