---
title: "Mary Test Flexdash"
output: 
  flexdashboard::flex_dashboard:
    theme:
      version: 4
      bootswatch: sandstone
runtime: shiny
---

```{r}
library(leaflet)
library(tidyverse)
library(sf)
library(readr)
library(shiny)
```

```{r, label = "reading in csvs", include = FALSE}
numbers <-read_csv("numbers.csv")

with_wiki <- read_csv("wiki_parks_data.csv")

parks <- read_csv("parks_updated.csv")

park_polygons <- read_sf("Dnr_Stat_Plan_Areas_Prk.geojson") |>
  mutate(legislative_name = str_replace_all(legislative_name, "\\.", ""),
         legislative_name = ifelse(legislative_name == "St Croix State Park", "Saint Croix State Park", legislative_name))
```

Scatterplot (kind of, unhelpful)
==========================

Inputs {.sidebar}
-------------------------

```{r, echo = FALSE}
inputPanel(
  selectInput("scatterplotx", label = "x-axis variable:",
              choices = c("Visitation" = "total",
                          "Year of Visit" = "visit_year",
                          "Season" = "Season",
                          "Park Size (acres)" = "Acres",
                          "County of Park" = "County or Counties",
                          "Year Established" = "Year")),
  selectInput("scatterploty", label = "y-axis variable:",
              choices = c("Visitation" = "total",
                          "Year of Visit" = "visit_year",
                          "Season" = "Season",
                          "Park Size (acres)" = "Acres",
                          "County of Park" = "County or Counties",
                          "Year Established" = "Year")),
  selectInput("color", label = "grouping variable:",
              choices = c("Season" = "Season",
                          "Year of Visit" = "visit_year",
                          "County of Park" = "County or Counties",
                          "Year Established" = "Year"))
)
```


Column
--------------------------
```{r echo = FALSE}
renderPlot({
  ggplot(numbers, aes(x = .data[[input$scatterplotx]], y = .data[[input$scatterploty]], color = .data[[input$color]])) + 
    geom_point()
})
```



Bar Chart (looks better)
==========================

Inputs {.sidebar}
-------------------------

```{r, echo = FALSE}
inputPanel(
  selectInput("boxx", label = "x-axis variable:",
              choices = c("Year of Visit" = "visit_year",
                          "Visitation" = "total",
                          "Season" = "Season",
                          "Park Size (acres)" = "Acres",
                          "County of Park" = "County or Counties",
                          "Year Established" = "Year")),
  selectInput("boxy", label = "y-axis variable:",
              choices = c("Visitation" = "total",
                          "Year of Visit" = "visit_year",
                          "Season" = "Season",
                          "Park Size (acres)" = "Acres",
                          "County of Park" = "County or Counties",
                          "Year Established" = "Year")),
  selectInput("color", label = "grouping variable:",
              choices = c("Season" = "Season",
                          "Year of Visit" = "visit_year",
                          "County of Park" = "County or Counties",
                          "Year Established" = "Year"))
)
```

Feel free to change around the variables with this bar chart as well! Our suggestion is x = Year of Visit, y = Visitation, grouping variable = Season, but explore other combinations as well!

Column
--------------------------
```{r echo = FALSE}
renderPlot({
  ggplot(numbers, aes(x = .data[[input$boxx]], y = .data[[input$boxy]], color = .data[[input$color]], fill = .data[[input$color]])) + 
    geom_col()
})
```
