---
title: "Mary"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r}
#| include: FALSE

library(tidyverse)
library(rvest)
library(polite)
library(pdftools)
```

```{r}
southern <- list("Big Stone Lake State Park", "Blue Mounds State Park", "Camden State Park", "Carley State Park", "Flandrau State Park", "Fort Ridgely State Park", "Frontenac State Park", "Helmer Myre State Park", "John Latsch State Park", "Killen Woods State Park", "Minneopa State Park", "Nerstrand Woods State Park", "O L Kipp State Park", "Sakatah State Park", "Sibley State Park", "Split Rock Creek State Park", "Upper Sioux Agency State Park", "Whitewater State Park", "Beaver Creek Valley State Park", "Forestville Mystery Cave State Park", "Great River Bluffs State Park", "John A Latsch State Park", "Kilen Woods State Park", "Lac qui Parle State Park", "Lake Louise State Park","Monson Lake State Park", "Myre-Big Island State Park", "Nerstrand Big Woods State Park", "Rice Lake State Park", "Sakatah Lake State Park")

heartland <- list("Buffalo River State Park", "Charles A Lindbergh State Park", "Father Hennepin State Park", "Glacial Lakes State Park", "Hayes Lake State Park", "Itasca State Park", "Lake Bemidji State Park", "Lake Bronson State Park", "Lake Carlos State Park", "Maplewood State Park", "Mille Lacs Kathio State Park", "Old Mill State Park", "Zippel Bay State Park", "Crow Wing State Park", "Glendalough State Park")


metro <- list("Afton State Park", "Fort Snelling State Park", "Interstate State Park", "Lake Maria State Park", "Saint Croix Wild River State Park", "William O'Brien State Park")

arrowhead <- list("Banning State Park", "George H Crosby Manitou State Park", "Gooseberry Falls State Park", "Jay Cooke State Park", "Judge C R Magney State Park", "Kadunce River State Park", "Saint Croix State Park", "Scenic State Park", "Split Rock Lighthouse State Park", "Temperance River State Park", "Tettegouche State Park", "Bear Head Lake State Park", "Cascade River State Park", "Franz Jevne State Park", "Franz Jevne State Park", "Grand Portage State Park", "Lake Vermilion-Soudan Underground Mine State Park", "McCarthy Beach State Park", "Moose Lake State Park", "Savanna Portage State Park", "Schoolcraft State Park", "Wild River State Park")

numbers <- numbers |>
  mutate(region = case_when(name %in% southern ~ "Southern",
                            name %in% heartland ~ "Heartland",
                            name %in% metro ~ "Metro",
                            name %in% arrowhead ~ "Arrowhead",
                            TRUE ~ as.character(name))) |>
  filter(region == "Southern" | region == "Heartland" | region == "Arrowhead" | region == "Metro")
```

```{r}
session <- bow("https://en.wikipedia.org/wiki/List_of_Minnesota_state_parks", force = TRUE)

result <- scrape(session) |>
  html_nodes(css = "table") |>
  html_table(header = TRUE, fill = TRUE)
try <- result[[1]]
try <- try[-1,]
try <- try[,-4]
try <- try |> rename(Acres = `Size[9]`)
```


```{r}
test <- try |>
  mutate(`Park name` = str_replace_all(`Park name`, "[.]", "")) |>
  mutate(`Park name` = str_replace_all(`Park name`, "[/]", " ")) |>
  mutate(`Park name` = case_when(`Park name` == "Nerstrand-Big Woods State Park" ~ "Nerstrand Big Woods State Park",
            .default = `Park name`))

```

```{r}
with_wiki <- with_wiki |>
  mutate(Acres = parse_number(Acres)) |>
  rename(Year = `Year Established[4]`) |>
  mutate(Year = str_sub(Year, 1, 4))
```

```{r}
with_wiki |>
  ggplot(aes(x = Year, y = Acres)) +
  geom_point()

with_wiki |>
  ggplot(aes(x = Acres, y = Year)) +
  geom_point()

with_wiki |>
  
  
```

```{r}
visits <- read_csv("Seasonal_summary.csv")

total_visits <- visits |>
  filter (`Unit type` == "State Park") |>
  group_by(`Park name`) |>
  mutate(total = sum(`Vehicle visits`)) |>
  distinct(`Park name`, .keep_all = TRUE) |>
  select(`Park name`, `System`, `Implementing agency`, `Unit type`, `total`) |>
  rename(name = `Park name`) |>
  mutate(name = str_c(name, " State Park"))

write.csv(total_visits, "total_visits.csv")
```

```{r}
with_wiki |>
  left_join(total_visits) |> 
  select(name, total, Acres, `Year Established[4]`) |>
  rename(year = `Year Established[4]`) |>
  mutate(year = str_sub(year, 1, 4))
```  

```{r}
numbers |>
  ggplot(aes(x = total, y = year)) +
  geom_point()

```

```{r}
visits <- read_csv("Seasonal_summary.csv")

seasonal_visits <- 
  visits |>
  filter (`Unit type` == "State Park") |>
  group_by(`Park name`, Season) |>
  mutate(total = sum(`Vehicle visits`)) |>
  distinct(`Park name`, .keep_all = TRUE) |>
  select(`Park name`, `System`, `Implementing agency`, `Unit type`, `total`) |>
  rename(name = `Park name`) |>
  mutate(name = str_c(name, " State Park"))

write.csv(seasonal_visits, "seasonal_visits.csv")
```

```{r}
visits <- read_csv("Seasonal_summary.csv")

by_season_visits <- 
  visits |>
  filter (`Unit type` == "State Park") |>
  mutate(Season = str_sub(Season, 1, -6)) |>
  group_by(`Park name`, Season) |>
  mutate(total = sum(`Vehicle visits`)) |>
  distinct(`Park name`, .keep_all = TRUE) |>
  select(`Park name`, `System`, `Implementing agency`, `Unit type`, `total`) |>
  rename(name = `Park name`) |>
  mutate(name = str_c(name, " State Park"))

write.csv(by_season_visits, "by_season_visits.csv")
```

```{r}
#joins visitation data with acres and year established data from wikipedia
numbers <- 
  with_wiki |>
  left_join(by_season_visits) |> 
  select(name, Season, total, Acres, Year) |>
  mutate(Year = str_sub(Year, 1, 4))

write.csv(numbers, "numbers.csv")
```

```{r}
numbers |>
  ggplot(aes(x = total, y = Year, color = Season)) +
  geom_point() 
```


```{r}
season <- read_csv("seasonal_visits.csv")
```

```{r}
season |>
  mutate(visit-year = str_sub(Season, -4, -1)) |>
  mutate(Season = str_extract(Season, "[^-]+"))

```

Column 
-------------------------

### Palmer Penguins

```{r echo = FALSE}
renderPlot({
  ggplot(numbers, aes(x = bill_length_mm,
              y = body_mass_g,
              color = species)) +
    geom_point() +
    geom_smooth(method = lm, se = FALSE) +
    labs(x = "Bill length (mm)", 
         title = "Body mass (g)")
})
```

```{r echo = FALSE}
renderPlot({
  ggplot(numbers, aes(x = total,
                      y = Year,
                      color = Season)) +
    geom_point() +
    labs(x = "Visitation (Car Counts)", 
         y = "Year Park Established",
         title = "Visitation by Year Park Established and Season")
})
```

```{r, eval = FALSE, include = FALSE}
ggplot(p, aes(x = bill_length_mm,
              y = body_mass_g,
              color = species)) +
  geom_point() +
  geom_smooth(method = lm, se = FALSE)
```




```{r, echo=FALSE}
inputPanel(
  selectInput("n_breaks2", label = "Number of bins:",
              choices = c(5, 10, 15, 20, 25, 30), selected = 15),
  
  sliderInput("bw_adjust2", label = "Bandwidth adjustment:",
              min = 0.1, max = 3, value = 1.2, step = 0.1)
)
```

Column 
-------------------------

### Geyser Eruption Duration

```{r echo = FALSE}
renderPlot({
  ggplot(faithful, aes(x = eruptions)) +
    geom_histogram(aes(y = ..density..), 
                   bins = as.numeric(input$n_breaks2),
                   fill = "white", colour = "black") +
    geom_density(adjust = input$bw_adjust2, colour = "blue") +
    labs(x = "Duration (minutes)", 
         title = "Geyser eruption duration")
})
```



```{r, eval = FALSE, include = FALSE}
# First write code that works, then incorporate into renderPlot
ggplot(faithful, aes(x = eruptions)) +
  geom_histogram(aes(y = ..density..), 
                 bins = 15,
                 fill = "white", colour = "black") +
  geom_density(adjust = 1.2, colour = "blue") +
  labs(x = "Duration (minutes)", 
       title = "Geyser eruption duration")
```

```{r}
ggplot(numbers, aes(x = Year)) +
  geom_histogram(aes(y = total),
                 bins = 15,
                 fill = "white", colour = "black") +
  geom_density(adjust = 1.2, color = "blue")

```


```{r}
numbers |>
  ggplot(aes(x = total, fill = Season, colour = Season)) +
    geom_density()

```

Scatterplot
==========================

Inputs {.sidebar}
--------------------------

```{r, echo = FALSE}
inputPanel(
  selectInput("scatterplotx", label = "x-axis variable:",
              choices = c("Bill Length" = "bill_len",
                          "Flipper Length" = "flipper_len",
                          "Bill Depth" = "bill_dep",
                          "Body Mass" = "body_mass")),
  selectInput("scatterploty", label = "y-axis variable:",
              choices = c("Bill Length" = "bill_len",
                          "Flipper Length" = "flipper_len",
                          "Bill Depth" = "bill_dep",
                          "Body Mass" = "body_mass")),
  selectInput("color", label = "grouping variable:",
              choices = c("Sex" = "sex",
                          "Species" = "species",
                          "Island" = "island"))
)
```


Column
--------------------------
```{r echo = FALSE}
renderPlot({
  ggplot(penguins, aes(x = .data[[input$scatterplotx]], y = .data[[input$scatterploty]], color = .data[[input$color]])) + 
    geom_point()
})
```

```{r}
numbers |>
  ggplot(aes(x = visit_year, color = Season, fill = Season)) +
  geom_col(aes(y = total))


```