---
title: "Part3_Final"
format: html
---

```{r}
#| include: FALSE

library(tidyverse)
library(rvest)
library(polite)
```


## Getting lists of parks
```{r}
robotstxt::paths_allowed("https://stateparks.com/") #tests if we can scrape


session <- bow("https://stateparks.com/minnesota_parks_and_recreation_destinations.html", force = TRUE)

#better version?
parks_text <- scrape(session) |> #reads all of the text on the minnesota home page 
  html_nodes("#parklink a") |> #pulls a list of all parks and recreation destinations in minnesota
  html_text() #makes the list into a text list

#mn_parks <- read_html("https://stateparks.com/minnesota_parks_and_recreation_destinations.html") #reads all of the text on the minnesota home page 

#parks_list <- html_nodes(mn_parks, "#parklink a") #pulls a list of all parks and recreation destinations in minnesota 

#parks_text <- html_text(parks_list) #makes the list into a text list
```

## test - writing a formula
```{r}
form <- parks_text[1] |>
  str_to_lower() |>
  str_replace_all(c(" " = "_", "'" = "", "wildlife_mgmt." = "state_wildlife_management")) #for each park, the text is changed to lower case and put into snake case (_ instead of spaces) -- also takes care of differences between text displayed and urls

url <- str_c("https://stateparks.com/", form, "_in_minnesota.html") #to create a list of the urls, this sets up the beginning and end of the url (which is the same for every park)


# formula -- generates urls we can scrape (only in mn) (adds the unique park name to the url for each list item)  --------------------------
url_list <- vector("character")
for (i in 1:length(parks_text)) {
  form <- parks_text[i] |>
  str_to_lower() |>
  str_replace_all(c(" " = "_", "'" = "", "wildlife_mgmt." = "state_wildlife_management"))
  url <- str_c("https://stateparks.com/", form, "_in_minnesota.html")
  url_list <- c(url_list, url)
}
```

```{r}
#This works! Kind of? It only pulls 44 paragraphs, and even if the code was working perfectly it would leave out 2 state parks (total 52). If I do 51 or 52 to has a an error (open.connection(x, "rb") ?)
#using the list of urls, pulls the first paragraph of information for each state park
paragraph_list <- vector("character")
iteration <- 1
for (i in 1:50) {
  mn_park_ex <- read_html(url_list[iteration])
  paragraph <- html_nodes(mn_park_ex, ".clearfix+ .psbod")
  paragraph <- html_text(paragraph)
  paragraph_list <- c(paragraph_list, paragraph) 
  iteration <- iteration + 1
}
```


## scraping the first paragraph

```{r}
# function using bow/scrape for finding paragraphs in parks 
scrape_page <- function(url) {
  Sys.sleep(5) # this follows the website requests for a crawl delay
  session <- bow(url, force = TRUE) #setting polite session
  scrape(session) |>
    html_nodes("#overview :nth-child(5)") |> #css selector for the first paragraphs of the page
    html_text() # converts to text
}

# function using bow/scrape for finding paragraphs in parks (option 2)
scrape_page2 <- function(url) {
  Sys.sleep(5)
  session <- bow(url, force = TRUE)
  scrape(session) |>
    html_nodes("#overview .psbod") |>
    html_text()
}

# i think both of these work? I used the first but we could probably pick either


# scraping the parks -----------------------------------------------------------
paragraph_list <- vector("character") # creates an empty character vector
for (i in 1:length(url_list)) { # iterates through the entire list of urls
  park_url <- url_list[i] # saves the current url
  paragraph <- scrape_page(park_url) # uses the scrape_page function above
  paragraph_list <- c(paragraph_list, paragraph) # appends the new paragraph to the list
}

print(paragraph_list) #checking
```

# cleaning paragraphs

```{r}
#cleaning the paragraph list-- not perfect, it removes both extra empty strings AND those indicating no paragraph was available
park_par_tbl <- paragraph_list |>
  str_subset("[a-zA-Z]+") |> #removes strings that don't contain words
  str_subset("Email:|Picnickingyes", negate = TRUE) # removes extra rows that were only recorded on some pages # turns it into a viewable tibble


# adding in missing rows -------------------------------------------------------
indexes <- c(9, 11, 20, 26, 37, 40, 107, 109, 110, 112, 113, 114, 115) # indexes of parks with missing paragraphs: cascade river, father hennepin, helmer myre, kadunce river, o l kipp, st croix wild river, boekholt grove, cooks, coon lake, little elk, malardi lake, talcot lake, teiken-dalve

for (i in 1:13) {
  park_par_tbl <- append(park_par_tbl, "", after = indexes[i])
}
```


## scraping addresses

```{r}
# function for scraping addresses -- we could rename
scrape_page3 <- function(url) {
  Sys.sleep(5)
  session <- bow(url, force = TRUE)
  scrape(session) |>
    html_nodes(".parkinfo div:nth-child(1)") |> # css selector for the address box,
    html_text()                                 # but it selects park name as well
}

# checking it works on individual urls
Sys.sleep(5)
session <- bow("https://stateparks.com/badoura_state_forest_in_minnesota.html", force = TRUE)
scrape(session) |>
  html_nodes(".parkinfo div:nth-child(1)") |>
    html_text()

# scraping addresses
address_list <- vector("character")
for (i in 1:length(url_list)) {
  park_url2 <- url_list[i] # different because it wasn't working and I was testing things-- I don't know if this is necessary
  address <- scrape_page3(park_url2)
  address_list <- c(address_list, address) 
}

viewing <- address_list |>
  as_tibble()

# address list has a lot of extra characters that aren't visible in the tibble, and I haven't cleaned it yet
```

## cleaning addresses
```{r}
cleaned_addresses <- address_list |>
  # replace line breaks and tabs with spaces
  str_replace_all("[\r\n\t]", " ") |>
  #replace multiple spaces with a single space
  str_replace_all("  +", " ") |>
  #remove email addresses
  str_replace("Email:.*$", "") |>
  #remove phone numbers  
  str_replace("Phone:.*$", "") |>
  #remove reservation info
  str_replace("Reservations:.*$", "") |>
  str_replace_all("^[^\\d]*", "") # removes the extra park name at the front
```

# making the final tidy tibble
```{r}
#the initial tidy tibble
final_parks <- tibble(
  name = parks_text,
  url = url_list,
  address = cleaned_addresses,
  description = park_par_tbl
) |> 
  mutate_all(na_if,"")

# adding park type
final_parks <- final_parks |>
  mutate(type = case_when(
    str_detect(parks_text, "State Park") ~ "state park",
    str_detect(parks_text, "State Forest") ~ "state forest",
    str_detect(parks_text, "Mgmt. Area") ~ "wildlife management area",
    str_detect(parks_text, "National Park") ~ "national park",
    str_detect(parks_text, "National Forest") ~ "national forest",
    str_detect(parks_text, "Wildlife Refuge") ~ "wildlife refuge"
  ))
```

